# commit to be tagged for the new release
commit = "HEAD"

project_name = "git-verify-chain"
github_repo = "talos-systems/git-verify-chain"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

previous = "v0.0.1"
pre_release = false

preface = """\
Initial release.
"""

[notes]
